name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      imageToBuild:
        description: 'component to build'
        required: true
        default: 'busy-box'
        type: choice
        options:
        - busy-box
        - nginx
      tagImage:
        description: 'please add tag'
        required: true
        default: 'latest'
jobs:
  push_image:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN_1 }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ inputs.imageToBuild }}
          push: true
          tags: ghcr.io/nickvab/${{ inputs.imageToBuild }}:${{ inputs.tagImage }}
  notification:
    needs: push_image
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack SUCCESS notification
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_CHANNEL: nickvab_git
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Message
          SLACK_MESSAGE: 'Image ${{ github.repository }}:${{ github.ref_name }} was pushed with SUCCESS result'
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Send Slack FAIL notification
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_CHANNEL: nickvab_git
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Message
          SLACK_MESSAGE: 'Image ${{ github.repository }}:${{ github.ref_name }} was pushed with FAIL result'
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
